<<<<<<< HEAD
=======
version: '4.0'
>>>>>>> c012aa7df1437f3e92e944c120d42f82aa8107e4

services:
  primary-kafka:
    image: apache/kafka:4.0.0
    container_name: primary-kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://primary-kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@primary-kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 5000

  standby-kafka:
    image: apache/kafka:4.0.0
    container_name: standby-kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9094,CONTROLLER://0.0.0.0:9095
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://standby-kafka:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@standby-kafka:9095
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  mm2:
    image: srividyatirumala/custom-mm2:latest  # pulls from Docker Hub first
    build:
      context: ../kafka-fork                    # fallback if image not found locally
      dockerfile: dockerfile
    container_name: mm2
    depends_on:
      - primary-kafka
      - standby-kafka
    command: >
      /opt/kafka/bin/connect-mirror-maker.sh /tmp/mm2.properties
    volumes:
      - ./mm2.properties:/tmp/mm2.properties
    ports:
      - "8083:8083"

  producer:
    image : srividyatirumala/kafka-producer:latest
    build: ./producer
    container_name: producer
    depends_on:
      - primary-kafka
